apiVersion: v1
kind: ConfigMap
metadata:
  name: bantam-config
  labels:
    app: bantam-shuttle
data:
  FRONTEND_URL: "http://localhost:5173"
  frontend-url: "http://localhost:5173"
  tracking-service-url: "http://tracking-service:8080"
  ai-service-url: "http://ai-service:8083"
