apiVersion: v1
kind: ConfigMap
metadata:
  name: bantam-config
  labels:
    app: bantam-shuttle
data:
  FRONTEND_URL: "http://shuttle.javajon-gke.duckdns.org"
  frontend-url: "http://shuttle.javajon-gke.duckdns.org"
  tracking-service-url: "http://shuttle.javajon-gke.duckdns.org/api/tracking"
  ai-service-url: "http://shuttle.javajon-gke.duckdns.org/api/ai"
