apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elite-dev

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  # - ingress.yaml  # TODO: Uncomment when domain is available

commonLabels:
  app.kubernetes.io/name: bantam-shuttle-backend
  app.kubernetes.io/part-of: elite-dev
  app.kubernetes.io/managed-by: kustomize

images:
  - name: bantam-shuttle-backend
    newName: harbor.javajon-gke.duckdns.org/library/elite-backend
    newTag: latest
