apiVersion: v1
kind: ServiceAccount
metadata:
  name: bantam-ai-service
  namespace: elite-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bantam-ai-service
  namespace: elite-dev
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bantam-ai-service
  namespace: elite-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bantam-ai-service
subjects:
- kind: ServiceAccount
  name: bantam-ai-service
  namespace: elite-dev
