apiVersion: v1
kind: Secret
metadata:
  name: bantam-ai-secret
  namespace: elite-dev
type: Opaque
stringData:
  AI_DATABASE_URL: ${AI_DATABASE_URL}
  AI_SUPABASE_URL: ${AI_SUPABASE_URL}
  AI_SUPABASE_KEY: ${AI_SUPABASE_KEY}
  AI_DB_PASSWORD: ${AI_DB_PASSWORD}
  AI_OPENAI_API_KEY: ${AI_OPENAI_API_KEY}
  OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
