apiVersion: v1
kind: Secret
metadata:
  name: bantam-ai-secret
  namespace: elite-dev
type: Opaque
stringData:
  # AI_OPENAI_API_KEY: ${OPENAI_API_KEY}
  # AI_DB_PASSWORD: ${AI_DB_PASSWORD}
  # AI_DATABASE_URL: ${AI_DATABASE_URL}
  # AI_SUPABASE_KEY: ${AI_SUPABASE_KEY}
  # AI_SUPABASE_URL: ${AI_SUPABASE_URL}
  # OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
  AI_DATABASE_URL: postgresql://postgres.bwijyokpoqewpwbwwfso:ctrl-alt-elite@aws-1-us-east-2.pooler.supabase.com:6543/postgres
  AI_SUPABASE_URL: https://bwijyokpoqewpwbwwfso.supabase.co
  AI_SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aWp5b2twb3Fld3B3Ynd3ZnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MDEzOTAsImV4cCI6MjA3ODM3NzM5MH0.MSCu6_IqWdbuYjCL3Pndb_y5dgYdBqF-hs76qAGEAdY
  AI_DB_PASSWORD: ctrl-alt-elite
  AI_OPENAI_API_KEY: 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
  OPENWEATHER_API_KEY: 0b5f5afbeda38b9b780a3d9258b7d0ba
  # RabbitMQ Password
  RABBITMQ_PASSWORD: guest