apiVersion: v1
kind: Service
metadata:
  name: bantam-ai-service
  namespace: elite-dev
  labels:
    app: bantam-ai-service
spec:
  type: ClusterIP
  selector:
    app: bantam-ai-service
    app.kubernetes.io/name: bantam-ai-service
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: kustomize
  ports:
  - name: http
    port: 8083
    targetPort: http
    protocol: TCP
