apiVersion: v1
kind: Service
metadata:
  name: bantam-ai-service
  namespace: elite-dev
  labels:
    app: bantam-ai-service
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: bantam-ai-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
