apiVersion: v1
kind: Service
metadata:
  name: bantam-shuttle-backend
  namespace: elite-dev
  labels:
    app: bantam-shuttle-backend
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: bantam-shuttle-backend
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600