apiVersion: v1
kind: ConfigMap
metadata:
  name: bantam-config
  namespace: elite-dev
  labels:
    app: bantam-shuttle
data:
  frontend-url: "http://bantam-shuttle.duckdns.org"
  tracking-service-url: "http://bantam-shuttle-tracking.elite-dev.svc.cluster.local:8081/api/tracking"
  ai-service-url: "http://bantam-ai-service.elite-dev.svc.cluster.local:8083/api/ai"