apiVersion: v1
kind: Service
metadata:
  name: bantam-shuttle-tracking
  namespace: elite-dev
  labels:
    app: bantam-shuttle-tracking
    tier: backend
    team: ctrl-alt-elite
spec:
  type: ClusterIP
  selector:
    app: bantam-shuttle-tracking
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
