# src/main/resources/application.yml
spring:
  application:
    name: tracking-service
  # rabbitmq:
  #   host: ${RABBITMQ_HOST:localhost}
  #   port: ${RABBITMQ_PORT:5672}
  #   username: ${RABBITMQ_USER:guest}
  #   password: ${RABBITMQ_PASS:guest}
  #   virtual-host: /
  #   publisher-confirm-type: correlated
  #   publisher-returns: true


server:
  port: ${PORT:8080}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics


# app:
#   rabbit:
#     exchange: geo.location.v1
#     push-queue: geo.push.live
#     latest-queue: geo.proc.latest