apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  # - ingress.yaml  # TODO: Uncomment when domain is available

commonLabels:
  app.kubernetes.io/name: bantam-shuttle-frontend
  app.kubernetes.io/part-of: elite-dev
  app.kubernetes.io/managed-by: kustomize

images:
  - name: bantam-shuttle-frontend
    newName: harbor.javajon-gke.duckdns.org/library/elite-frontend
    newTag: latest
