apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bantam-shuttle

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: bantam-shuttle-frontend
  app.kubernetes.io/part-of: bantam-shuttle
  app.kubernetes.io/managed-by: kustomize

images:
  - name: bantam-shuttle-frontend
    newName: gabbykoms/bantam-shuttle-frontend
    newTag: latest
