apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elite-dev

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: bantam-shuttle-tracking
  app.kubernetes.io/part-of: bantam-shuttle
  app.kubernetes.io/managed-by: kustomize

images:
  - name: bantam-shuttle-tracking
    newName: harbor.javajon-gke.duckdns.org/library/elite-tracking-service
    newTag: latest

secretGenerator:
  - name: tracking-secrets
    envs:
      - ./.env